"""5x7 bitmap font used by the formation example.

Each glyph is a 7-tuple of 5-character strings. Space = off pixel; any other
character = on pixel. Row 0 is the top of the glyph.
"""

GRID_W = 5
GRID_H = 7

FONT_5X7: dict[str, tuple[str, ...]] = {
    " ": (
        "     ",
        "     ",
        "     ",
        "     ",
        "     ",
        "     ",
        "     ",
    ),
    "A": (
        " XXX ",
        "X   X",
        "X   X",
        "XXXXX",
        "X   X",
        "X   X",
        "X   X",
    ),
    "B": (
        "XXXX ",
        "X   X",
        "X   X",
        "XXXX ",
        "X   X",
        "X   X",
        "XXXX ",
    ),
    "C": (
        " XXXX",
        "X    ",
        "X    ",
        "X    ",
        "X    ",
        "X    ",
        " XXXX",
    ),
    "D": (
        "XXXX ",
        "X   X",
        "X   X",
        "X   X",
        "X   X",
        "X   X",
        "XXXX ",
    ),
    "E": (
        "XXXXX",
        "X    ",
        "X    ",
        "XXXX ",
        "X    ",
        "X    ",
        "XXXXX",
    ),
    "F": (
        "XXXXX",
        "X    ",
        "X    ",
        "XXXX ",
        "X    ",
        "X    ",
        "X    ",
    ),
    "G": (
        " XXXX",
        "X    ",
        "X    ",
        "X  XX",
        "X   X",
        "X   X",
        " XXX ",
    ),
    "H": (
        "X   X",
        "X   X",
        "X   X",
        "XXXXX",
        "X   X",
        "X   X",
        "X   X",
    ),
    "I": (
        "XXXXX",
        "  X  ",
        "  X  ",
        "  X  ",
        "  X  ",
        "  X  ",
        "XXXXX",
    ),
    "J": (
        "XXXXX",
        "   X ",
        "   X ",
        "   X ",
        "   X ",
        "X  X ",
        " XX  ",
    ),
    "K": (
        "X   X",
        "X  X ",
        "X X  ",
        "XX   ",
        "X X  ",
        "X  X ",
        "X   X",
    ),
    "L": (
        "X    ",
        "X    ",
        "X    ",
        "X    ",
        "X    ",
        "X    ",
        "XXXXX",
    ),
    "M": (
        "X   X",
        "XX XX",
        "X X X",
        "X   X",
        "X   X",
        "X   X",
        "X   X",
    ),
    "N": (
        "X   X",
        "XX  X",
        "X X X",
        "X X X",
        "X X X",
        "X  XX",
        "X   X",
    ),
    "O": (
        " XXX ",
        "X   X",
        "X   X",
        "X   X",
        "X   X",
        "X   X",
        " XXX ",
    ),
    "P": (
        "XXXX ",
        "X   X",
        "X   X",
        "XXXX ",
        "X    ",
        "X    ",
        "X    ",
    ),
    "Q": (
        " XXX ",
        "X   X",
        "X   X",
        "X   X",
        "X X X",
        "X  X ",
        " XX X",
    ),
    "R": (
        "XXXX ",
        "X   X",
        "X   X",
        "XXXX ",
        "X X  ",
        "X  X ",
        "X   X",
    ),
    "S": (
        " XXXX",
        "X    ",
        "X    ",
        " XXX ",
        "    X",
        "    X",
        "XXXX ",
    ),
    "T": (
        "XXXXX",
        "  X  ",
        "  X  ",
        "  X  ",
        "  X  ",
        "  X  ",
        "  X  ",
    ),
    "U": (
        "X   X",
        "X   X",
        "X   X",
        "X   X",
        "X   X",
        "X   X",
        " XXX ",
    ),
    "V": (
        "X   X",
        "X   X",
        "X   X",
        "X   X",
        "X   X",
        " X X ",
        "  X  ",
    ),
    "W": (
        "X   X",
        "X   X",
        "X   X",
        "X   X",
        "X X X",
        "XX XX",
        "X   X",
    ),
    "X": (
        "X   X",
        "X   X",
        " X X ",
        "  X  ",
        " X X ",
        "X   X",
        "X   X",
    ),
    "Y": (
        "X   X",
        "X   X",
        " X X ",
        "  X  ",
        "  X  ",
        "  X  ",
        "  X  ",
    ),
    "Z": (
        "XXXXX",
        "    X",
        "   X ",
        "  X  ",
        " X   ",
        "X    ",
        "XXXXX",
    ),
}
